### ISSUE TITLE
Change container user to a non-root user

### ISSUE THREAD

**Issue by eerkunt** [contino/docker-terraform#3]
This will also require a change in README.md

**Comment by mrserverless** [comment]
Sounds like a good idea. @lucas044 what you think?

**Comment by lucasteligioridis** [comment]
Definitely think this is a good idea...
Since terraform runs it creates all the .terraform/* files on the host machine with root ownership after bind mounting etc...

I've been meaning to refactor this repo a bit, I'll include this change in the refactor as well. :+1:
